/* ==========================================================================
   Geo&Land — static-hosting helper
   For hosts that cannot run server.js (Netlify, Vercel, GitHub Pages…):
   run `node scripts/sync-env.js` (or `npm run sync-env`) after editing .env
   to write the values into assets/js/env.js, then deploy the folder.
   ========================================================================== */

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const OUT_FILE = path.join(ROOT, "assets", "js", "env.js");

function loadEnv() {
  const out = {};
  if (!fs.existsSync(ENV_FILE)) return out;
  fs.readFileSync(ENV_FILE, "utf8")
    .split(/\r?\n/)
    .forEach(function (line) {
      const m = line.match(/^\s*([A-Za-z0-9_.-]+)\s*=\s*(.*)\s*$/);
      if (!m) return;
      let value = (m[2] || "").trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      out[m[1]] = value;
    });
  return out;
}

const env = loadEnv();

const body =
  "/* Generated by scripts/sync-env.js from .env — do not edit by hand. */\n" +
  "window.GEOLAND_ENV = " +
  JSON.stringify(
    {
      SUPABASE_URL: env.SUPABASE_URL || "",
      SUPABASE_ANON_KEY: env.SUPABASE_ANON_KEY || ""
    },
    null,
    2
  ) +
  ";\n";

fs.writeFileSync(OUT_FILE, body, "utf8");

console.log("Wrote " + path.relative(ROOT, OUT_FILE));
console.log(
  env.SUPABASE_URL && env.SUPABASE_ANON_KEY
    ? "Supabase configured → " + env.SUPABASE_URL
    : "Warning: SUPABASE_URL / SUPABASE_ANON_KEY are empty in .env"
);
