-- Geo&Land Kosova — Supabase schema
-- Run this once in the Supabase SQL editor (Dashboard → SQL → New query → Run).

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  base text unique not null,
  original_name text default '',
  alt text default '',
  width integer,
  height integer,
  widths text default '',
  is_upload integer default 1,
  created_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text not null check (category in ('gis-agri', 'software', 'cadastre', 'forestry')),
  year integer,
  org text default '',
  description text default '',
  image_media_id bigint references public.media (id),
  featured integer default 0,
  featured_rank integer default 100,
  published integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.project_images (
  project_id bigint not null references public.projects (id) on delete cascade,
  media_id bigint not null references public.media (id),
  sort integer default 100,
  primary key (project_id, media_id)
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  anchor text unique not null,
  name text not null,
  short_scope text default '',
  scope_items text default '',
  scope_paragraph text default '',
  deliverables text default '',
  image_media_id bigint references public.media (id),
  sort integer default 100,
  published integer default 1,
  updated_at timestamptz default now()
);

create table if not exists public.milestones (
  id bigint generated by default as identity primary key,
  year integer not null,
  text text not null,
  sort integer default 100,
  published integer default 1,
  updated_at timestamptz default now()
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  ts timestamptz default now(),
  actor text not null default '',
  action text not null,
  entity text not null,
  entity_id bigint,
  summary text not null
);

create index if not exists projects_published_idx on public.projects (published, year desc);
create index if not exists projects_slug_idx on public.projects (slug);
create index if not exists services_sort_idx on public.services (sort);
create index if not exists milestones_year_idx on public.milestones (year desc);
create index if not exists activity_id_idx on public.activity (id desc);

-- Row level security -------------------------------------------------------

alter table public.media enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;
alter table public.services enable row level security;
alter table public.milestones enable row level security;
alter table public.activity enable row level security;

drop policy if exists "Public read media" on public.media;
create policy "Public read media" on public.media for select using (true);

drop policy if exists "Public read published projects" on public.projects;
create policy "Public read published projects" on public.projects for select using (published = 1);

drop policy if exists "Public read published services" on public.services;
create policy "Public read published services" on public.services for select using (published = 1);

drop policy if exists "Public read published milestones" on public.milestones;
create policy "Public read published milestones" on public.milestones for select using (published = 1);

drop policy if exists "Public read gallery" on public.project_images;
create policy "Public read gallery" on public.project_images for select using (true);

-- The admin panel performs writes with the service role server-side, which
-- bypasses RLS. These policies additionally allow any signed-in user to manage
-- content directly through the Supabase API.
drop policy if exists "Authenticated manage media" on public.media;
create policy "Authenticated manage media" on public.media for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated manage projects" on public.projects;
create policy "Authenticated manage projects" on public.projects for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated manage project images" on public.project_images;
create policy "Authenticated manage project images" on public.project_images for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated manage services" on public.services;
create policy "Authenticated manage services" on public.services for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated manage milestones" on public.milestones;
create policy "Authenticated manage milestones" on public.milestones for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated read activity" on public.activity;
create policy "Authenticated read activity" on public.activity for select to authenticated using (true);

drop policy if exists "Authenticated write activity" on public.activity;
create policy "Authenticated write activity" on public.activity for insert to authenticated with check (true);

-- Storage bucket for uploaded images ---------------------------------------

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read media bucket" on storage.objects;
create policy "Public read media bucket" on storage.objects
  for select using (bucket_id = 'media');

drop policy if exists "Authenticated upload media bucket" on storage.objects;
create policy "Authenticated upload media bucket" on storage.objects
  for insert to authenticated with check (bucket_id = 'media');

drop policy if exists "Authenticated update media bucket" on storage.objects;
create policy "Authenticated update media bucket" on storage.objects
  for update to authenticated using (bucket_id = 'media') with check (bucket_id = 'media');

drop policy if exists "Authenticated delete media bucket" on storage.objects;
create policy "Authenticated delete media bucket" on storage.objects
  for delete to authenticated using (bucket_id = 'media');
